export const category={

    GET_ALL_CATEGORY_REQUEST:"GET_ALL_CATEGORY_REQUEST",
    GET_ALL_CATEGORY_SUCCE:"GET_ALL_CATEGORY_SUCCE",
    GET_ALL_CATEGORY_FAILD:"GET_ALL_CATEGORY_FAILD",
    ADD_CATEGORY_REQUEST:"ADD_ALL_CATEGORY_REQUEST",
    ADD_CATEGORY_SUCCE:"ADD_ALL_CATEGORY_SUCCE",
    ADD_CATEGORY_FAILD:"ADD_ALL_CATEGORY_FAILD",
    DELETE_CATEGORY_REQUEST:"DELETE_CATEGORY_REQUEST",
    DELETE_CATEGORY_SUCCE:"DELETE_CATEGORY_SUCCE",
    DELETE_CATEGORY_FAILD:"DELETE_CATEGORY_FAILD",
    UPDATE_CATEGORY_REQUEST:"UPDATE_CATEGORY_REQUEST",
    UPDATE_CATEGORY_SUCCE:"UPDATE_CATEGORY_SUCCE",
    UPDATE_CATEGORY_FAILD:"UPDATE_CATEGORY_FAILD"



}