export const productA={

    GET_ALL_PRODUCT_REQUEST:"GET_ALL_PRODUCT_REQUEST",
    GET_ALL_PRODUCT_REQUEST_SUCCE:"GET_ALL_PRODUCT_REQUEST_SUCCE",
    GET_ALL_PRODUCT_FAILD:"GET_ALL_PRODUCT_FAILD",

    GET_ALL_PRODUCT_BYPRICE_REQUEST:"GET_ALL_PRODUCT_BYPRICE_REQUEST",
    GET_ALL_PRODUCT_BYPRICE_REQUEST_SUCCE:"GET_ALL_PRODUCT_BYPRICE_REQUEST_SUCCE",
    GET_ALL_PRODUCT_BYPRICE_FAILD:"GET_ALL_PRODUCT_BYPRICE_FAILD",
    GET_SUGGESION_REQUEST:"GET_SUGGESION_REQUEST",
    GET_SUGGESION_SUCCE:"GET_SUGGESION_SUCCE",
    GET_SUGGESION_FAILD:"GET_SUGGESION_FAILD",

    GET_DISCOUNT_REQUEST:"GET_DISCOUNT_REQUEST",
    GET_DISCOUNT_SUCCE:"GET_DISCOUNT_SUCCE",
    GET_DISCOUNT_FAILD:"GET_DISCOUNT_FAILD",



    ADD_PRODUCT_REQUEST:"ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCE:"ADD_PRODUCT_SUCCE",
    ADD_PRODUCT_FAILD:"ADD_PRODUCT_FAILD",
    ADD_PRODUCTPictures_REQUEST:"ADD_PRODUCTPictures_REQUEST",
    ADD_PRODUCTPictures_SUCCE:"ADD_PRODUCTPictures_SUCCE",
    ADD_PRODUCTPictures_FAILD:"ADD_PRODUCTPictures_FAILD",
    ADD_PRODUCTDISCOUNT_REQUEST:"ADD_PRODUCTDISCOUNT_REQUEST",
    ADD_PRODUCTDISCOUNT_SUCCE:"ADD_PRODUCTDISCOUNT_SUCCE",
    ADD_PRODUCTDISCOUNT_FAILD:"ADD_PRODUCTDISCOUNT_FAILD",

    DELETE_PRODUCT_REQUEST:"DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SUCCE:"DELETE_PRODUCT_SUCCE",
    DELETE_PRODUCT_FAILD:"DELETE_PRODUCT_FAILD",

    UPDATE_PRODUCT_REQUEST:"UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCE:"UPDATE_PRODUCT_SUCCE",
    UPDATE_PRODUCT_FAILD:"UPDATE_PRODUCT_FAILD",

    DELETE_PRODUCTDISCCOUNT_REQUEST:"DELETE_PRODUCTDISCCOUNT_REQUEST",
    DELETE_PRODUCTDISCCOUNT_SUCCE:"DELETE_PRODUCTDISCCOUNT_SUCCE",
    DELETE_PRODUCTDISCCOUNT_FAILD:"DELETE_PRODUCTDISCCOUNT_FAILD",



}