export const souscategory={

    GET_ALL_SOUSCATEGORY_REQUEST:"GET_ALL_SOUSCATEGORY_REQUEST",
    GET_ALL_SOUSCATEGORY_SUCCE:"GET_ALL_SOUSCATEGORY_SUCCE",
    GET_ALL_SOUSCATEGORY_FAILD:"GET_ALL_SOUSCATEGORY_FAILD",
    ADD_SOUSCATEGORY_REQUEST:"ADD_SOUSCATEGORY_REQUEST",
    ADD_SOUSCATEGORY_SUCCE:"ADD_SOUSCATEGORY_SUCCE",
    ADD_SOUSCATEGORY_FAILD:"ADD_SOUSCATEGORY_FAILD",
    DELETE_SOUSCATEGORY_REQUEST:"DELETE_SOUSCATEGORY_REQUEST",
    DELETE_SOUSCATEGORY_SUCCE:"DELETE_SOUSCATEGORY_SUCCE",
    DELETE_SOUSCATEGORY_FAILD:"DELETE_SOUSCATEGORY_FAILD",
    UPDATE_SOUSCATEGORY_REQUEST:"UPDATE_SOUSCATEGORY_REQUEST",
    UPDATE_SOUSCATEGORY_SUCCE:"UPDATE_SOUSCATEGORY_SUCCE",
    UPDATE_SOUSCATEGORY_FAILD:"UPDATE_SOUSCATEGORY_FAILD"



}