export const types={

    GET_ALL_TYPES_REQUEST:"GET_ALL_TYPES_REQUEST",
    GET_ALL_TYPES_SUCCE:"GET_ALL_TYPES_SUCCE",
    GET_ALL_TYPES_FAILD:"GET_ALL_TYPES_FAILD",
    ADD_TYPES_REQUEST:"ADD_TYPES_REQUEST",
    ADD_TYPES_SUCCE:"ADD_TYPES_SUCCE",
    ADD_TYPES_FAILD:"ADD_TYPES_FAILD",
    DELETE_TYPES_REQUEST:"DELETE_TYPES_REQUEST",
    DELETE_TYPES_SUCCE:"DELETE_TYPES_SUCCE",
    DELETE_TYPES_FAILD:"DELETE_TYPES_FAILD",
    UPDATE_TYPES_REQUEST:"UPDATE_TYPES_REQUEST",
    UPDATE_TYPES_SUCCE:"UPDATE_TYPES_SUCCE",
    UPDATE_TYPES_FAILD:"UPDATE_TYPES_FAILD"



}