export const user={
    verify_USER_REQUEST:"verify_USER_REQUEST",
    verify_USER_SUCCESS:"verify_USER_SUCCESS",
    verify_USER_FAILD:"verify_USER_FAILD"   ,
    ADD_USER_REQUEST:"verify_USER_REQUEST",
    ADD_USER_SUCCESS:"verify_USER_SUCCESS",
    ADD_USER_FAILD:"verify_USER_FAILD",
    CONNECT_USER_REQUEST:"CONNECT_USER_REQUEST",
    CONNECT_USER_SUCCESS:"CONNECT_USER_SUCCESS",
    CONNECT_USER_FAILD:"CONNECT_USER_FAILD",
    CONFIG_SUCCESS:"CONFIG_SUCCESS",
    CONFIG_REQUEST:"CONFIG_REQUEST",
    CONFIG_FAILD:"CONFIG_FAILD"



}